### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.terraformersmc.terraform.boat.impl.TerraformBoatTypeImpl.<init>(net.minecraft.class_1792, net.minecraft.class_1792)'

### ISSUE THREAD

**Issue by otavio-silva** [BloomhouseMC/Bewitchment-Plus#14]
See [this issue](https://github.com/MoriyaShiine/bewitchment/issues/327), I believe it is affecting Bewitchment Plus as well.

**Comment by SteveNichols5** [comment]
Seeing this issue with Bewitchment plus as well -
[crash-2022-10-27_12.25.35-client.txt](https://github.com/BloomhouseMC/Bewitchment-Plus/files/9881550/crash-2022-10-27_12.25.35-client.txt)
