### ISSUE TITLE
Spam in Client Logs

### ISSUE THREAD

**Issue by DracoTijandor** [BloomhouseMC/Bewitchment-Plus#3]
**Minecraft:** 1.18.2
**Fabric:** 0.14.6
**Bewitchment:** 1.18-20
**Bewitchment Plus:** 1.18.2-16

Whenever I am near a Leonard statue, my logs are flooded with one these messages:
[Render thread/INFO]: [STDOUT]: bwplus:textures/block/statues/statue_leonard_blackstone.png
[Render thread/INFO]: [STDOUT]: bwplus:textures/block/statues/statue_leonard_netherbrick.png
[Render thread/INFO]: [STDOUT]: bwplus:textures/block/statues/statue_leonard_gold.png

All other statues work without any spam in the logs. Is there a way to fix this?

**Comment by DatuStram** [comment]
I have the exact same issue, using the exact same Minecraft, Fabric, and mods versions.

**Comment by mrsterner** [comment]
Well yes obviously i forgot a System.out.println in there, will fix some day i have time
