### ISSUE TITLE
ME Crafting Terminal Issue with Bewitchment Plus

### ISSUE THREAD

**Issue by ghost** [BloomhouseMC/Bewitchment-Plus#31]
I can´t craft anything else than "1337 Fleece" when all crafting slots are used.

**Comment by mrsterner** [comment]
I need more info, what version of bewitchment plus are you using?

**Comment by ghost** [comment]
Its the version bewitchmentplus-1.19-11.jar. I am playing a Modpack called Prominence Fabric.

**Comment by ghost** [comment]
If u restart it works again
