### ISSUE TITLE
Bug whit artifacts mod

### ISSUE THREAD

**Issue by SerSwett** [BloomhouseMC/Bewitchment-Plus#7]
All necklace items from artifact can't be equip they got overwritten whit no slots. Other items work fine thought.
mc 1.18.2
fabric-api-0.57.0
bewitchmentplus-1.18.2-17
artifacts-7.0.3+fabric
and other mods but works fine.

**Comment by Desynq** [comment]
They haven't backported the recent commit that fixes the issue in 1.19 to 1.18.2.
https://github.com/BloomhouseMC/Bewitchment-Plus/pull/8
